/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TransactionsAddRouteImport } from './routes/transactions/add'

const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsAddRoute = TransactionsAddRouteImport.update({
  id: '/transactions/add',
  path: '/transactions/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/transactions/add' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/transactions/add' | '/transactions'
  id: '__root__' | '/transactions/add' | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TransactionsAddRoute: typeof TransactionsAddRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/add': {
      id: '/transactions/add'
      path: '/transactions/add'
      fullPath: '/transactions/add'
      preLoaderRoute: typeof TransactionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TransactionsAddRoute: TransactionsAddRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
